### ISSUE TITLE
hope can filter the topics.

### ISSUE THREAD

**Issue by RandyChen1985** [redpanda-data/console#741] opened 2023-06-20 09:37 UTC
i have too much topics,  hope can filter to display ..
![image](https://github.com/redpanda-data/console/assets/1704661/f6543ae0-34ce-485c-978f-75f271412061)
![image](https://github.com/redpanda-data/console/assets/1704661/adbfbe92-04f4-4438-9562-c59c64b35cf3)

**Comment by RandyChen1985** [comment] 2023-06-20 09:52
![image](https://github.com/redpanda-data/console/assets/1704661/67a2048d-1c54-487d-a79c-94a05cb155bd)

like this ..

**Comment by weeco** [comment] 2023-06-20 10:35
In the table header (for the topic name) there's the magnifier icon. Click on that. The UI/UX for that is not intuitive, but we will improve that. Duplicate of #288

**Closed** 2023-06-20 10:35 UTC

**Comment by RandyChen1985** [comment] 2023-06-20 10:37
tks!
