### ISSUE TITLE
Make api request when switching pages

### ISSUE THREAD

**Issue by sago2k8** [redpanda-data/console#641] opened 2023-03-01 12:28 UTC
Simple video of an example on our cloud environment.

https://www.loom.com/share/288462a0396749b39d33fb470addf009

"I created a new topic but neither the metrics nor the topics tabs picked that up, only when I went to schema registry did it refresh the state there." @lilic comment.

I did check and seems that we don't refresh on any page change it's periodic every 30s (keep me true @rikimaru0345), and it was just a coincidence when page switching.

**Comment by jvorcak** [comment] 2024-01-03 08:59
I think it's a duplicate of https://github.com/redpanda-data/console/issues/857#event-11292248237, I'll pick it up now.

**Closed** 2024-01-04 18:52 UTC
Labels: bug, frontend
