### ISSUE TITLE
Unable to Establish WebSocket Connection When Accessing Console via Uberproxy

### ISSUE THREAD

**Issue by OuesFa** [redpanda-data/console#765] opened 2023-07-13 17:41 UTC
Hello,

I'm having trouble establishing a WebSocket connection to the redpanda-console when accessed via an uberproxy in my Kubernetes cluster.

Problem:
When I try to access the redpanda-console through the uberproxy, I can't see the list the messages for a given topic.
On my browser inspect I see this error 
```
WebSocket connection to 'wss://kowl.preprod-1.blbl.cr/api/topics/fraud-servix-event/messages' failed:
```
And I see the following error in the console's pod logs:
```
{"level":"error","ts":"2023-07-13T17:30:46.987Z","msg":"failed to upgrade HTTP connection to websocket connection","error":"failed to upgrade websocket in messages endpoint websocket: request origin not allowed by Upgrader.CheckOrigin"}
```
The error suggests that the WebSocket server is refusing to upgrade the connection because it doesn't allow the uberproxy's origin.

The redpanda-console and the uberproxy are running in the same Kubernetes cluster but in different namespaces and on different nodes.

The uberproxy service is configured to point to the redpanda-console like so:

```yaml
- fqdn: redpanda-console-platform-kafka....
  serviceName: redpanda-console
  namespace: platform
  port: 8080
  optional_vhost_directives:
    RewriteEngine: 'On'
    RewriteCond: '%{HTTP:Upgrade} websocket [NC]'
    RewriteCond: '%{HTTP:Connection} upgrade [NC]'
    RewriteRule: '.* "ws://redpanda-console.platform.svc.cluster.local:8080%{REQUEST_URI}" [P]'
```
I have tried setting the `allowedOrigins` in the console's configuration in my HR values at `spec.values.console.config.server.allowedOrigins` to both ["http://uberproxy.infra.svc.cluster.local:8080"] and ["*"], but the issue persists.

The issue does not occur when I port-forward the pod responsible for the UI. This suggests that the problem lies with the WebSocket configurations on the uberproxy side, or with how the redpanda-console handles WebSocket connections from the uberproxy.

Could you provide some guidance on how to configure the redpanda-console and the uberproxy to allow WebSocket connections? It would be ideal if the console could accept connections from the uberproxy, as this is a crucial part of our deployment.

Thanks in advance for your help.
Fares

**Comment by weeco** [comment] 2023-07-14 09:23
Hey @OuesFa ,
I'm not familiar with uberproxy, but I can give the following input:

1. The `*` allowed origin is not supported, hence it won't help you.
2. I believe the required allowed origin you want to set is `https://kowl.preprod-1.blbl.cr` because this may be the origin that is forwarded by your proxy. If this does not work please let me know and we can add a log message that shows what origin was requested instead.

**Comment by OuesFa** [comment] 2023-07-17 08:01
Hey 👋 

This worked fine! I missed that the origin forwarded by the proxy is indeed the url you suggested.
I think it would be helpful anyway to add the log message showing what origin was requested. Wdyt?

Thanks so much for your help!

**Comment by weeco** [comment] 2023-07-17 09:27
Thanks for reporting back. Yes would be good to add it anyways. Let's leave this issue open, I labeled it accordingly.

**Comment by zymergen-samira** [comment] 2023-08-10 18:44
I'm having a similar difficulties -- I have an app from which I'm trying to query the redpanda-console API. I set `server.allowedOrigins` to permit traffic from my app's domain, but I'm still unable to connect, and I see this error in redpanda-console's logs:

```
"error":"failed to upgrade websocket in messages endpoint websocket: request origin not allowed by Upgrader.CheckOrigin"
```

Here's the config specified in my Helm chart:

```
console:
  config:
    server:
      allowedOrigins:
        - myapp.mydomain.com
      listenPort: 8080
     kafka:
       # ... kafka broker configuration
```

I can also reproduce this issue locally using the [example docker-compose](https://github.com/redpanda-data/console/blob/dd77c0e5bbf1cb26057fc1b8add2061a56d7b86e/docs/local/docker-compose.yaml#L20-L41) setup, by adding a `server.allowedOrigins` to the provided config yaml on [this line](https://github.com/redpanda-data/console/blob/dd77c0e5bbf1cb26057fc1b8add2061a56d7b86e/docs/local/docker-compose.yaml#L27). Even if I set `server.allowedOrigins`, I can't connect from the hosts that I specified, and I see a `request origin not allowed` error message in the console's logs. It seems `server.allowedOrigins` isn't working the way I expect? Am I not configuring it correctly?

**Comment by weeco** [comment] 2023-08-10 18:53
In the docker compose file you should not set the `allowedOrigins` property and I don't have any indication that it's not working as intended. The issue is only open to improve the logging so that it's clear what origin was used (and rejected) as this was causing the confusion for the author of this issue.

Can you describe your setup/usecase why you think you need to set an allowedOrigin? I think this is only needed in very specific situations where the frontend is hosted under a different hostname as the backend.

**Comment by twmb** [comment] 2023-10-19 15:52
Fixed in next release improvements.

**Closed by twmb** 2023-10-19 15:52 UTC
Labels: feature, help wanted, backend
