### ISSUE TITLE
Change text/tooltip  for Estimated Message/Record counts

### ISSUE THREAD

**Issue by jason-da-redpanda** [redpanda-data/console#1224] opened 2024-04-22 14:58 UTC
The message count displayed in Console ..

We already have a message saying that the calculation(HighWaterMark-LogStartOffset)  for topics defined as `cleanup.policy=compact*`....
as gaps in offsets can occur when compaction occurs. 

but in the scenario of topics defined as 'cleanup.policy=delete`  (or compact) .. there can also be apparent gaps ...
when using transactions to produce events. This is down to internal control records..which are not consumed by standard clients....

Which means the count is an estimate regardless of the cleanup.policy

Suggestion is 

- change wording to say "Estimate Message Count" (or varation)
- Have a tooltip to detail reasons for deltas

**Comment by weeco** [comment] 2024-06-11 09:34
Closing this as a duplicate of https://github.com/redpanda-data/console/issues/1064

**Closed by weeco** 2024-06-11 09:34 UTC
Labels: frontend
