### ISSUE TITLE
monaco editor for used connect configuration does not work with basePath

### ISSUE THREAD

**Issue by acristu** [redpanda-data/console#690] opened 2023-05-04 06:01 UTC
When running with `basePath: "/console"` the editor does not load as it tries to load static js files from `/static` instead of `/console/static`
```
GET http://<host>/static/js/vendor/monaco/package/min/vs/loader.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by rikimaru0345** [comment] 2023-05-04 14:29
Unfortunately I cannot reproduce this, do you have any additional information about this?

Maybe some sort of browser caching issue?

We are setting the path to get monaco here: https://github.com/redpanda-data/console/blob/master/frontend/src/config.ts#L137

Which gets set from `getBasePath()`, and should result in the same path as the api uses as its prefix.

Please try to open the chrome developer tools, then click and hold the refresh button until the menu opens, and select the 3rd option "clear cache and reload".

Also please check whether or not the base path is set properly in the `<head>` section, in these 2 locations:

![image](https://user-images.githubusercontent.com/28133019/236238011-fb129282-9be9-4621-ac30-6b5cbb9c3f88.png)

My screenshots are from development mode, so the values are not set, but for you it should say `/console` instead of `__BASE_PATH_REPLACE_MARKER__`.  Please check if that is the case.

**Comment by weeco** [comment] 2023-05-09 19:29
Closing this for now as we were not able to reproduce and haven't got additional information yet.

**Closed by weeco** 2023-05-09 19:29 UTC
Labels: bug, frontend

**Comment by acristu** [comment] 2023-05-12 03:52
hi @weeco , sry for the delay, my setup is working because I was able to set another `/` path to the k8s Ingress besides the `/console`, so requests to `/static/.....` are handled correctly.

So the base looks correct but there are still some absolute URLs:
![image](https://github.com/redpanda-data/console/assets/6796822/24003ba6-0b57-4c46-a437-b599c5cec6e5)

I'm using version `docker.redpanda.com/vectorized/console:master-8fcce39`

**Comment by weeco** [comment] 2023-05-12 08:53
@acristu Before re-opening this issue I notice that you are using a rather old Docker image, could you try this Docker image and see if the issue is also present in a relatively new Docker image: `docker.redpanda.com/redpandadata/console-unstable:master-0f75bd8`
