### ISSUE TITLE
users/authorization in kowl

### ISSUE THREAD

**Issue by onacht** [redpanda-data/console#594] opened 2023-01-08 15:00 UTC
hi
i need to give to specific user user RO permissions in KOWL is there any support for users or authorization in kowl?

**Comment by weeco** [comment] 2023-01-08 16:09
Hi @onacht ,
I assume I can close this as a duplicate of https://github.com/redpanda-data/console/issues/593 ?

**Closed** 2023-01-08 22:21 UTC
