### ISSUE TITLE
Console is not displaying any messages if the message includes gibberish characters

### ISSUE THREAD

**Issue by moming00** [redpanda-data/console#610] opened 2023-02-03 03:12 UTC
I have a topic with 100 messages, and each messages includes a few characters that failed to convert to a specific charset. In this case, I would expect the message still be visible, and the gibberish character be showing as black square or question mark or any mark saying the character is problematic. But the fact is Console says "No messages" and with "Size 1.27MB, Messages 200".

please see the difference between Console and Kafka UI.
![image](https://user-images.githubusercontent.com/73276360/216503420-a478f8ca-a475-4b4e-ab66-6547c17aa91a.png)
![image](https://user-images.githubusercontent.com/73276360/216503664-02e0d576-08b5-4e74-ba01-4b13cb3372bc.png)

**Comment by weeco** [comment] 2023-02-04 17:00
Thanks @moming00 ,
can you provide us with the value (hex encoded) so that I can try to debug this? As far as I can tell this should be rendered as a hex string in Console and I've seen this working. Happy to test against a certain docker compose as well of course

**Comment by moming00** [comment] 2023-02-06 09:27
> Thanks @moming00 , can you provide us with the value (hex encoded) so that I can try to debug this? As far as I can tell this should be rendered as a hex string in Console and I've seen this working. Happy to test against a certain docker compose as well of course

can you have a try with the attached text file?
[topic-message.txt](https://github.com/redpanda-data/console/files/10661560/topic-message.txt)

**Comment by moming00** [comment] 2023-02-23 06:10
Hello @weeco , any news on this issue? It's little bit annoying that we have to use the command tools to check what's inside the msg.

**Comment by weeco** [comment] 2023-02-23 09:48
@moming00 In fact I'd expect messages to show up, but rendered as hex string. Just rendering them as string even though we know it's not ASCII would render a lot of binary messages as a string which seems less useful to me. Your given example obviously makes sense to me and thus we should ideally have this selectable by the user.

The real question to me is why you don't see any messages at all for your topic. Could you shed some light into this? Does the message consumption work on other topics (sometimes users have problems because we use Websockets for transmitting the messages)?

**Comment by moming00** [comment] 2023-02-23 14:21
> @moming00 In fact I'd expect messages to show up, but rendered as hex string. Just rendering them as string even though we know it's not ASCII would render a lot of binary messages as a string which seems less useful to me. Your given example obviously makes sense to me and thus we should ideally have this selectable by the user.
> 
> The real question to me is why you don't see any messages at all for your topic. Could you shed some light into this? Does the message consumption work on other topics (sometimes users have problems because we use Websockets for transmitting the messages)?

I believe that's because my current topic is full of these messages. And other topic is working fine.

**Comment by weeco** [comment] 2023-07-10 21:11
Since we were not able to reproduce the issue I'm going to close this. If you can provide a setup to reproduce the issue I'm happy to take a look at it.

**Closed by weeco** 2023-07-10 21:11 UTC
Labels: bug
