### ISSUE TITLE
basePath config not working since 2.1.0

### ISSUE THREAD

**Issue by cfl-agatward** [redpanda-data/console#564] opened 2022-12-01 15:10 UTC
Since upgrading to v2.1.0, this configuration in a config file does not appear to work:

server:
  basePath: console
  setBasePathFromXForwardedPrefix: false

**Comment by weeco** [comment] 2022-12-01 15:15
Hey @cfl-agatward ,
could you share what version you have upgraded from and some more details about what exactly isn't working with this feature?

**Comment by cfl-agatward** [comment] 2022-12-01 15:21
Sure.   The environment is using the containers from Docker Hub, on an arm64 node in AWS.  The previous container version was 2.0.3, which works perfectly.

After the upgrade, it appears the basePath in the config file is being ignored.  The file did not change between versions and is mounted at the same location - everything else in the config file is being picked up correctly - brokers, tls, sasl, it's just the basePath not working.

Verification has been done both through the reverse proxy which sits in front, and by forming an SSH tunnel through to localhost:8080 and accessing the path specified in the config, which returns 404.   Swapping the container back to v2.0.3 makes it work perfectly immediately with no other changes.

**Comment by voyc-geoffrey** [comment] 2022-12-15 09:22
I can confirm that the same is happening on our side. We are running it through AWS ECS ( pulling the docker container ) and settings:
KAFKA_BROKERS = d01.examplebroker.com
SERVER_BASEPATH = redpanda

This runs through an AWS ALB, which forwards the traffic to redpanda. The behavior is weird.

If I don't set the basepath it tries to pull everything from exampledomain.com/* even when navigating to exampledomain.com/redpanda. If I set the basepath to redpanda, I can actually load the page, however it tries to still pull a duplicate of /static/js/main.4df9d53a.js and /embedded.js from the base domain. 

To make matter weirder, if I navigate to exampledomain.com/redpanda it gives a query error page, however clicking anywhere else loads the actual page on exampledomain.com/topic ( if you were to click on topic ), instead of exampledomain.com/redpanda/topic.

Switching to version v2.0.3 fixes all the issues.

**Comment by sap1ens** [comment] 2022-12-23 19:22
I can confirm I see the same issue when trying to upgrade from `master-8fcce39` to `v2.1.1`. Makes it completely unusable.

**Comment by mpwsh** [comment] 2023-02-03 21:23
Can confirm this is happening with the latest version

**Comment by weeco** [comment] 2023-02-07 10:03
Hey all, I'm sorry for the delay handling this. Just wanted to give an heads-up here that it's on my radar, but I haven't had the time to look at this yet. I hope to have a look at this within the next 3-4 weeks.

**Comment by weeco** [comment] 2023-02-16 23:30
This should be fixed now. Could someone here test the fix to get additional confidence before we put this into the next release?

```
docker pull redpandadata/console-unstable:master-0b1e37d
```

**Comment by weeco** [comment] 2023-02-17 14:19
I'll close this issue for now, please let us know if the issue persists with the latest version (v2.2.0 or a newer version built against master)

**Comment by Allsimon** [comment] 2023-03-05 09:34
I took me a while to figure out that the basePath shouldn't be prefixed by a slash

For example, if you want to host to `mysite.com/foobar/` the configuration is:
```diff
server:
-  basePath: "/foobar/"
+  basePath: "foobar/"
```

**Comment by Allsimon** [comment] 2023-03-05 10:06
I don't think this is fixed, with this configuration:
```yaml
server:
  basePath: "foobar/"
  setBasePathFromXForwardedPrefix: false
  stripPrefix: true
```

and going to http://localhost:8080/foobar/
- 2.0.3 works fine ✅ 
- 2.1.0 UI loads but is unusable with a `404 Path:/foobar/ Query:""`  ❌ 
- 2.2.0 <-> 2.2.2 responds with a HTTP 200 but Content-Length: 0 ❌

**Comment by weeco** [comment] 2023-03-07 22:16
@Allsimon sorry for that, I think this PR may fix it: https://github.com/redpanda-data/console/pull/646

Do you mind testing the following docker image? `redpandadata/console-unstable:call-next-routers-after-basepath-middleware-0098df6`

**Closed** 2023-03-08 10:01 UTC
Labels: bug, backend

**Comment by sap1ens** [comment] 2024-04-08 22:41
Still seeing this in 2.4.5.
